# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 15:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(default='foo', max_length=100)),
                ('bookFile', models.FileField(null=True, upload_to='uploads/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_podcasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
